[activation]
scripts = ["development/pixi/activation.sh"]

[activation.env]
# Help ccache manage generated files and PCH (https://ccache.dev/manual/latest.html#_precompiled_headers)
CCACHE_SLOPPINESS = "include_file_ctime,include_file_mtime,pch_defines,time_macros"
CMAKE_COLOR_DIAGNOSTICS = "ON"
CMAKE_CXX_COMPILER_LAUNCHER = "ccache"
CMAKE_EXPORT_COMPILE_COMMANDS = "ON"

[dependencies]
benchmark = ">=1.9.4,<2"
catch2 = ">=3.8.0,<4"
ccache = ">=4.9.1"
cmake = ">=3.22"
cxx-compiler = ">=1.7.0"
eigen = ">=3.4.0,<4"
eigenpy = ">=3.12.0"
fmt = ">=11.1.4"
libboost-devel = ">=1.86.0,<2"
libboost-python-devel = ">=1.86.0,<2"
matplotlib-base = ">=3.9.4,<4"
meshcat-python = ">=0.3.2,<0.4"
mimalloc = ">=3.1.5,<4"
ninja = ">=1.0.0"
pkg-config = ">=0.29.2"
pytest = ">=8.3.5,<9"
python = ">=3.10.19"
typed-argument-parser = ">=1.10.1,<2"

[environments]
all = {features = [
  "crocoddyl",
  "doc",
  "openmp",
  "pinocchio",
  "python-latest"
], solve-group = "python-latest"}
all-python-oldest = {features = [
  "crocoddyl",
  "doc",
  "openmp",
  "pinocchio",
  "python-oldest"
], solve-group = "python-oldest"}
clang = {features = ["clang", "python-latest"]}
crocoddyl = {features = ["crocoddyl", "python-latest"], solve-group = "python-latest"}
default = {features = ["python-latest"], solve-group = "python-latest"}
lint = {features = ["lint"], solve-group = "python-latest"}
new-version = {features = [
  "crocoddyl",
  "new-version",
  "openmp",
  "pinocchio",
  "python-latest"
], solve-group = "python-latest"}
openmp = {features = ["openmp", "python-latest"], solve-group = "python-latest"}
pinocchio = {features = ["pinocchio", "python-latest"], solve-group = "python-latest"}
python-oldest = {features = ["python-oldest"], solve-group = "python-oldest"}
test-pixi-build = {features = ["test-pixi-build"], no-default-feature = true}
tracy = {features = ["python-latest", "tracy"], solve-group = "python-latest"}

# Use clang on GNU/Linux.
# We must use scripts instead of env to setup CC and CXX
# to avoid cxx-compiler to overwrite them.
[feature.clang]
activation = {env = {CC = "clang", CXX = "clang++"}}
dependencies = {clangxx = "*"}
platforms = ["linux-64"]

[feature.crocoddyl]
activation = {env = {ALIGATOR_CROCODDYL_COMPAT = "ON"}}
dependencies = {crocoddyl = ">=3.0.1"}

[feature.doc.dependencies]
doxygen = ">=1.13"
graphviz = ">=12"

[feature.lint]
dependencies = {pre-commit = ">=4.3.0"}
tasks = {lint = {cmd = "pre-commit run --all"}}

# Increment the version number with ALIGATOR_VERSION variable
[feature.new-version]

[feature.new-version.dependencies]
tomlkit = ">=0.13.2"

[feature.new-version.tasks]
configure-new-version = {cmd = [
  "-B",
  "-DBUILD_BENCHMARKS=ON",
  "-DBUILD_CROCODDYL_COMPAT=ON",
  "-DBUILD_EXAMPLES=ON",
  "-DBUILD_WITH_OPENMP_SUPPORT=ON",
  "-DBUILD_WITH_PINOCCHIO_SUPPORT=ON",
  "-DCMAKE_BUILD_TYPE=$ALIGATOR_BUILD_TYPE",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-DGENERATE_PYTHON_STUBS=ON",
  "-G",
  "-S",
  ".",
  "CXXFLAGS=$ALIGATOR_CXX_FLAGS",
  "Ninja",
  "build-new-version",
  "cmake"
]}
release-new-version = {cmd = "VERSION=$ALIGATOR_VERSION cmake --build build-new-version --target release", depends-on = [
  "configure-new-version"
]}

# Not supported by Windows (because of conda-forge issue)
[feature.openmp]

[feature.openmp.target.linux]
activation = {env = {ALIGATOR_OPENMP_SUPPORT = "ON"}}
dependencies = {libgomp = ">=14.2"}

[feature.openmp.target.osx]
activation = {env = {ALIGATOR_OPENMP_SUPPORT = "ON"}}
dependencies = {llvm-openmp = ">=19.1"}

[feature.pinocchio]
activation = {env = {ALIGATOR_PINOCCHIO_SUPPORT = "ON"}}
dependencies = {example-robot-data-loaders = ">=4", pinocchio = ">=3.8.0"}

[feature.python-latest.dependencies]
python = ">=3.14.0"

[feature.python-oldest.dependencies]
python = "3.10.*"

[feature.test-pixi-build]

[feature.test-pixi-build.dependencies]
aligator = {path = "."}
cmake = ">=3.22"
python = "*"

[feature.test-pixi-build.tasks]
test = {depends-on = ["test-cmake", "test-python"]}
test-cmake = "cmake -S tests/pixi_build -B build_test_pixi_build"
test-python = "python -c 'import aligator'"

# tracy-client is not built on osx-arm64
[feature.tracy]

[feature.tracy.target.linux-64]
activation = {env = {ALIGATOR_TRACY_ENABLE = "ON"}}
dependencies = {tracy-profiler-client = ">=0.11.1"}

[feature.tracy.target.osx-64]
activation = {env = {ALIGATOR_TRACY_ENABLE = "ON"}}
dependencies = {tracy-profiler-client = ">=0.11.1"}

[package]
name = {workspace = true}
version = {workspace = true}

[package.build]
backend = {name = "pixi-build-cmake", version = "*"}

[package.build.config]
extra-args = [
  "-DBUILD_BENCHMARKS=OFF",
  "-DBUILD_CROCODDYL_COMPAT=ON",
  "-DBUILD_EXAMPLES=OFF",
  "-DBUILD_TESTING=OFF",
  "-DBUILD_WITH_OPENMP_SUPPORT=ON",
  "-DBUILD_WITH_PINOCCHIO_SUPPORT=ON",
  "-DGENERATE_PYTHON_STUBS=ON"
]

[package.build-dependencies]
pkg-config = ">=0.29.2"

[package.host-dependencies]
crocoddyl = ">=3.0.1"
eigen = ">=3.4.0,<4"
eigenpy = "*"
fmt = ">=11.1.4"
libboost-devel = ">=1.86.0,<2"
libboost-python-devel = ">=1.86.0,<2"
mimalloc = ">=3.1.5,<4"
pinocchio = ">=3.8.0"
python = ">=3.9.22"
typed-argument-parser = ">=1.10.1,<2"

[package.target.linux.host-dependencies]
libgomp = ">=14.2"

[package.target.osx.host-dependencies]
llvm-openmp = ">=19.1"

[tasks]
build = {cmd = "cmake --build build --target all", depends-on = ["configure"]}
clean = {cmd = "rm -rf build"}
# We must avoid to set CMAKE_CXX_FLAGS because of WIN32
# https://discourse.cmake.org/t/strictly-appending-to-cmake-lang-flags/6478
configure = {cmd = [
  "-B",
  "-DALIGATOR_TRACY_ENABLE=$ALIGATOR_TRACY_ENABLE",
  "-DBUILD_BENCHMARKS=$ALIGATOR_BENCHMARKS",
  "-DBUILD_CROCODDYL_COMPAT=$ALIGATOR_CROCODDYL_COMPAT",
  "-DBUILD_EXAMPLES=$ALIGATOR_EXAMPLES",
  "-DBUILD_WITH_OPENMP_SUPPORT=$ALIGATOR_OPENMP_SUPPORT",
  "-DBUILD_WITH_PINOCCHIO_SUPPORT=$ALIGATOR_PINOCCHIO_SUPPORT",
  "-DCMAKE_BUILD_TYPE=$ALIGATOR_BUILD_TYPE",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-DGENERATE_PYTHON_STUBS=$ALIGATOR_PYTHON_STUBS",
  "-G",
  "-S",
  ".",
  "CXXFLAGS=$ALIGATOR_CXX_FLAGS",
  "Ninja",
  "build",
  "cmake"
]}
doc = {cmd = "cmake --build build --target doc", depends-on = ["configure"]}
test = {cmd = "ctest --test-dir build --output-on-failure", depends-on = [
  "build"
]}

[workspace]
channels = ["conda-forge"]
description = "A primal-dual augmented Lagrangian-type solver for trajectory optimization"
license = "BSD-2-Clause"
license-file = "LICENSE"
name = "aligator"
platforms = ["linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]
readme = "README.md"
repository = "https://github.com/Simple-Robotics/aligator"
version = "0.18.0"
