[build-system]
build-backend = "cmeel"
requires = [
  "cmeel-boost ~= 1.90.0",
  "cmeel-fmt[build]",
  "cmeel-mimalloc[build]",
  "cmeel[build]",
  "libcrocoddyl[build]",
  "libpinocchio[build]",
  "numpy"
]

[project]
dependencies = [
  "cmeel-boost ~= 1.90.0",
  "cmeel-fmt",
  "cmeel-mimalloc",
  "libcrocoddyl",
  "libpinocchio",
  "numpy"
]
description = "Versatile and efficient framework for constrained trajectory optimization"
license = "BSD-2-Clause"
name = "libaligator"
readme = "README.md"
requires-python = ">=3.10"
version = "0.19.1"

[tool.cmeel]
configure-args = [
  "-DBUILD_BENCHMARKS=OFF",
  "-DBUILD_CROCODDYL_COMPAT=ON",
  "-DBUILD_EXAMPLES=OFF",
  "-DBUILD_PYTHON_INTERFACE=OFF",
  "-DCOAL_DISABLE_HPP_FCL_WARNINGS=ON",
  "-DINSTALL_DOCUMENTATION=OFF"
]
has-sitelib = false

[tool.ruff.lint]
exclude = [".git", "build*", "cmake"]
fixable = ["E"]
ignore = ["E501"]
select = ["E", "F"]

[tool.ruff.lint.per-file-ignores]
"bindings/python/aligator/__init__.py" = ["F401", "F403"]
"bindings/python/aligator/utils/__init__.py" = ["F401", "F403"]

[tool.tomlsort]
all = true
